#!/usr/bin/env python
import os
import sys
import logging
import argparse


         
if __name__ == "__main__":
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument('--log-level', default='info', type=str,
                        help='Logging level, one of:  debug, info, warning, error, critical (default: info)')

    args = parser.parse_args()
    
    print(args)

    logging.basicConfig(stream=sys.stdout, level=getattr(logging, args.log_level.upper(), logging.INFO),
                        format='%(asctime)s - %(message)s', datefmt="%Y-%m-%d %H:%M:%S")
            